name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-project:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code từ GitHub về runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài đặt uv và tự động quản lý cache thư viện
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          # Tự động bật tính năng cache để lần chạy sau siêu nhanh
          enable-cache: true
          # Chỉ định phiên bản Python giống như dự án của cậu
          python-version: "3.10"

      # 3. Đồng bộ hóa và cài đặt các thư viện từ file uv.lock
      - name: Install dependencies
        run: uv sync --frozen

      # 4. Chạy file python của cậu
      - name: Run script
        run: uv run hello.py