name: My First Workflow

on: 
  push:

jobs: 
  demo:
    runs-on: ubuntu-latest

    steps: 
      - name: Download source code 
        uses: actions/checkout@v4
      
      - name: Hello user
        run: |
          echo "Chào bạn! Đây là hành động tự động Github Actions."
          echo "Người kích hoạt: ${{ github.actor }}"
          echo "Sự kiện kích hoạt: ${{ github.event_name }}"

      - name: Check Ubuntu version
        run: lsb_release -a

      - name: Setup uv 
        uses: astral-sh/setup-uv@v5
        with: 
          # Tự động bật tính năng cache để tải nhanh hơn
          enable-cache: true
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --frozen 

      - name: Run Python program 
        run: uv run main.py